var obj = {
    colxrhz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            align: 'center',
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            align: 'center',
            width: "70px",
        },
        {
            title: "入院诊断",
            dataIndex: "diagnosis",
            align: 'center',
            width: "270px",
        },
        {
            title: "时间",
            align: 'center',
            children: [{
                    title: "新入",
                    dataIndex: "admissionTime",
                    align: 'center',
                    width: 100,
                },
                {
                    title: "转入",
                    dataIndex: "transferTime",
                    align: 'center',
                    width: 100,
                },
            ],
        },
        {
            title: "入院方式",
            dataIndex: "method",
            align: 'center',
            width: "50px",
        },
        {
            title: "护理级别",
            dataIndex: "levelOfCare",
            align: 'center',
            width: "80px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            align: 'center',
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            align: 'center',
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            align: 'center',
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            dataIndex: "bp",
            align: 'center',
            width: "120px",

        },
        {
            title: "白班病情",
            dataIndex: "dayShiftCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "上夜病情",
            dataIndex: "lastNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "下夜病情",
            dataIndex: "nextNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    colcyhz: [{
            title: "床号",
            dataIndex: "bedNumber",
            align: 'center',
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            align: 'center',
            width: "70px",
        },
        {
            title: "出院诊断",
            align: 'center',
            dataIndex: "diagnosis",
        },
        {
            title: "时间",
            align: 'center',
            children: [{
                    title: "出院",
                    align: 'center',
                    dataIndex: "dischargeTime",
                    width: 150,
                },
                {
                    title: "转科",
                    align: 'center',
                    dataIndex: "transferTime",
                    width: 140,
                },
                {
                    title: "死亡",
                    align: 'center',
                    dataIndex: "timeOfDeath",
                    width: 140,
                },
            ],
        },
        {
            title: "转往科室",
            align: 'center',
            dataIndex: "transferInDepartmentName",
            width: 140,
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    colbzhz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            width: "70px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            width: "120px",
            dataIndex: "bp",
        },
        {
            title: "SPO2",
            dataIndex: "",
            scopedSlots: { customRender: "spo2" },
            width: "70px",
        },
        {
            title: "白班病情",
            dataIndex: "dayShiftCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "上夜病情",
            dataIndex: "lastNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "下夜病情",
            dataIndex: "nextNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    colbwhz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            width: "70px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            width: "120px",
            dataIndex: "bp",
        },
        {
            title: "SPO2",
            dataIndex: "",
            scopedSlots: { customRender: "spo2" },
            width: "70px",
        },
        {
            title: "白板病情",
            dataIndex: "dayShiftCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "上夜病情",
            dataIndex: "lastNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "下夜病情",
            dataIndex: "nextNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    coltshz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            width: "70px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            align: 'center',
            dataIndex: "bp",
            width: "120px",

        },
        {
            title: "诊断",
            dataIndex: "diagnosis",
        },
        {
            title: "护理级别",
            dataIndex: "levelOfCare",
        },
        {
            title: "特殊属性",
            dataIndex: "specialProperty",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    colsshz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            width: "70px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            dataIndex: "bp",
            width: "90px",

        },
        {
            title: "主要诊断",
            dataIndex: "diagnosis",
            width: "120px",
        },
        {
            title: "手术名称",
            dataIndex: "surgeryName",
            width: "120px",
        },
        {
            title: "时间",
            children: [{
                    title: "手术时间",
                    dataIndex: "surgeryTime",
                    width: 100,
                },
                {
                    title: "送回病房时间",
                    dataIndex: "returnTime",
                    width: 100,
                },
            ],
        },
        {
            title: "麻醉方式",
            dataIndex: "anesthesia",
            width: "120px",
        },
        {
            title: "白班病情",
            dataIndex: "dayShiftCondition",
            width: "120px",
        },
        {
            title: "上夜病情",
            dataIndex: "lastNightCondition",
            width: "120px",
        },
        {
            title: "下夜病情",
            dataIndex: "nextNightCondition",
            width: "120px",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    colyjhz: [{
            title: "床号",
            dataIndex: "bedNumber",
            sorter: (a, b) => a.bch.length - b.bch.length,
            width: "70px",
        },
        {
            title: "姓名",
            dataIndex: "patientName",
            width: "70px",
        },
        {
            title: "T(℃)",
            dataIndex: "t",
            scopedSlots: { customRender: "tw" },
            width: "60px",
        },
        {
            title: "P(次分)",
            dataIndex: "p",
            scopedSlots: { customRender: "p" },
            width: "70px",
        },
        {
            title: "R(次分)",
            dataIndex: "r",
            scopedSlots: { customRender: "r" },
            width: "70px",
        },
        {
            title: "BP(mmHg)",
            width: "120px",
            dataIndex: "bp",
        },
        {
            title: "SPO2",
            dataIndex: "",
            scopedSlots: { customRender: "spo2" },
            width: "70px",
        },
        {
            title: "白板病情",
            dataIndex: "dayShiftCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "上夜病情",
            dataIndex: "lastNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "下夜病情",
            dataIndex: "nextNightCondition",
            align: 'center',
            width: "150px",
        },
        {
            title: "操作",
            width: "120px",
            align: 'center',
            scopedSlots: { customRender: "address" },
        },
    ],
    showItem: [
        //读取过来护士选中那些项目需要展示
        { name: "hlShioverNewPatientDtos", columns: "colxrhz", title: "新入患者", isEnable: true },
        { name: "hlShioverDischargedPatientDtos", columns: "colcyhz", title: "出院患者", isEnable: true },
        { name: "hlShioverSeriouslyIllPatientDtos", columns: "colbzhz", title: "病重患者", isEnable: true },
        { name: "hlShioverCriticallyIllPatientDtos", columns: "colbwhz", title: "病危患者", isEnable: true },
        { name: "hlShioverFirstLevelNursingDtos", columns: "colyjhz", title: "一级护理", isEnable: true },
        { name: "hlShioverSurgicalPatientDtos", columns: "colsshz", title: "手术患者", isEnable: true },
        { name: "hlShioverSpecialPatientDtos", columns: "coltshz", title: "特殊患者", isEnable: true },
    ],
    topDataList: [
        //顶部数据的集合
        { title: "病人总数", name: 'patientCount', num: "99" },
        { title: "新入患者", name: 'newEntrantCount', num: "20" },
        { title: "转入", name: 'transferInCount', num: "11" },
        { title: "出院", name: 'dischargedCount', num: "" },
        { title: "转出", name: 'transferOutCount', num: "" },
        { title: "死亡", name: 'deathCount', num: "" },
        { title: "一级护理", name: 'firstLevelNursCount', num: "" },
        { title: "手术", name: 'surgeryCount', num: "" },
        { title: "分娩", name: 'childbirthCount', num: "" },
        { title: "病重", name: 'seriouslyIllCount', num: "" },
        { title: "病危", name: 'criticallyIllCount', num: "" },
        { title: "特殊", name: 'specialCount', num: "" },
    ]

}

export default obj